# https://github.com/zerostaticthemes/jekyll-serif-theme#github-pages
# baseurl: "/jekyll-theme/"

# lang: hr # overrides default en

css:
  selection_bg: '#1d9bf0'
  selection_text: '#fafdff'
  theme_paper: 'white'
  theme_ink: 'black'
  theme_dark_paper: '#15202b'
  theme_dark_ink: '#f7f9f9'
  button_bg: '#1d9bf0'
  button_label: '#fafdff'
  header_height: '2.5rem'
  header_bg: '#f7f9f9'
  transition-duration-slow: '0.9s'
  transition-duration-fast: '0.3s'
  easing: 'cubic-bezier(.4,0,0,1)'

  # using github's free font Mona Sans - https://github.com/github/mona-sans
  font_base: Mona Sans Regular
  # using fontshare's free font Zodiak - https://www.fontshare.com/fonts/zodiak
  # font_heading: Zodiak-Black
  # using fontshare's free font Literata - https://www.fontshare.com/fonts/literata
  font_heading: Literata-Medium

company_name: "YOUR_BRAND_NAME"

brand_name_description: "YOUR_BRAND_NAME logo"
brand_logo: true # if false text will be displayed
brand_svg: true # if false a png will be used

home:
  limit_works: 6
  # limit_works: # toggle if not used
  # limit_products: 3
  # limit_team: 3
  # limit_posts: 3
  limit_careers: 3

collections:
  team:
    output: true
  products:
    output: true
  stories:
    output: true

defaults:
  - scope:
      type: "products"
    values:
      layout: "post"
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-github-metadata # TODO - rate limited - setup at the end # https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

# environment: production # overrides jekyll.environment which is the default
