# https://github.com/zerostaticthemes/jekyll-serif-theme#github-pages
# baseurl: "/jekyll-theme/"

# lang: hr # overrides default en

css:
  selection_bg: '#0fc5b4'
  selection_text: '#d0fbf7'

  theme_paper: 'white'
  theme_ink: 'black'
  theme_dark_paper: 'black'
  theme_dark_ink: 'white'

  button_bg: '#0fc5b4'
  button_label: 'white'

  header_height: '4em'
  header_bg: '#0fc5b4'
  header_brand_link_height: 36px

  footer_padding_top: '2.5em'
  footer_padding_bottom: '0.5em'
  footer_bg: '#d0fbf7'
  footer_brand_link_height: 28px
  footer_socials_size: 1.5em
  footer_socials_space_between_items: 0.5em

  mobile_nav_bg: '#12edd9'
  mobile_current_bg: 'white'
  mobile_submenu_bg: '#d0fbf7'

  desktop_current_bg: 'white'
  desktop_nav_space_between_items: '1.5em'
  desktop_nav_text_size: '1.125em'
  desktop_nav_link_hover_bg: '#12edd9'
  desktop_nav_submenu_bg: '#12edd9'
  desktop_nav_submenu_hover_bg: '#89f6ec'
  desktop_nav_submenu_width: '16em'
  
  transition_duration_slow: '0.9s'
  transition_duration_fast: '0.3s'
  easing: 'cubic-bezier(.4,0,0,1)'

  # using github's free font Mona Sans - https://github.com/github/mona-sans
  font_base: Mona Sans Regular
  # using fontshare's free font Zodiak - https://www.fontshare.com/fonts/zodiak
  # font_heading: Zodiak-Black
  # using fontshare's free font Literata - https://www.fontshare.com/fonts/literata
  font_heading: Literata-Medium

# ends css

company_name: "YOUR_BRAND_NAME"
copyright_label: "All right reserved"

brand_name_description: "YOUR_BRAND_NAME logo"
brand_logo: true # if false text will be displayed
brand_svg: true # if false a png will be used

home:
  limit_works: 6
  # limit_works: # toggle if not used
  # limit_products: 3
  # limit_team: 3
  # limit_posts: 3
  limit_careers: 3

collections:
  team:
    output: true
  products:
    output: true
  stories:
    output: true

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-github-metadata # TODO - rate limited - setup at the end # https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

# environment: production # overrides jekyll.environment which is the default
