# https://github.com/zerostaticthemes/jekyll-serif-theme#github-pages
# baseurl: "/jekyll-theme/"

# lang: hr # overrides default en

company_name: "YOUR_BRAND_NAME"
copyright_label: "All right reserved"

brand_name_description: "YOUR_BRAND_NAME logo"
brand_logo: true # if false text will be displayed
brand_svg: true # if false a png will be used

home:
  limit_works: 3
  # limit_works: # toggle if not used
  limit_products: 3
  limit_team: 3
  limit_posts: 3
  limit_careers: 3

collections:
  work:
    output: true
  team:
    output: true
  products:
    output: true

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "work"
      type: "pages"
    values:
      layout: "list"
  - scope:
      path: "products"
      type: "pages"
    values:
      layout: "list"
  - scope:
      path: "team"
      type: "pages"
    values:
      layout: "list"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-github-metadata # TODO - rate limited - setup at the end # https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting

# environment: production # overrides jekyll.environment which is the default
