# lang: hr # overrides default en

a11y_skip: Skip to main content

company_name: "Kurian"
copyright_label: "All right reserved"

brand_name_description: "Kurian logo"
brand_logo: true # if false text will be displayed
brand_svg: true # if false a png will be used

home:
  limit_features: 3
  limit_services: 6
  # limit_products: 4
  # limit_team: 4
  # limit_posts: 5
  # limit_careers: 3

collections:
  # services:
  #   output: true # has to be commented out like this for some reason
  services:
    output: true
  products:
    output: true
  team:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  # -
  #   scope:
  #     path: "services"
  #     type: "pages"
  #   values:
  #     layout: "list"
  # - scope:
  #     path: "products"
  #     type: "pages"
  #   values:
  #     layout: "list"
  # - scope:
  #     path: "team"
  #     type: "pages"
  #   values:
  #     layout: "list"
  # - scope:
  #     path: "blog"
  #     type: "pages"
  #   values:
  #     layout: "list"
  # - scope:
  #     path: "careers"
  #     type: "pages"
  #   values:
  #     layout: "list"
  # - scope:
  #     path: "about"
  #     type: "pages"
  #   values:
  #     layout: "about"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "services"
    values:
      layout: "services-post"
  - scope:
      path: ""
      type: "products"
    values:
      layout: "products-post"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team-member"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# environment: production # overrides jekyll.environment which is the default







# Fallback SEO data
# SEE GUIDE HERE: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Kurian
tagline: the_best_OCCUPATION_NAME_in_CITY_NAME_COUNTRY_NAME
description: write_a_WEBSITE_description_around_160_characters_long # https://moz.com/learn/seo/meta-description
url: https://your-example-website.com
twitter:
  card: YOUR_TWITTER_HANDLE
  username: YOUR_TWITTER_SUMMARY
# facebook:
#   app_id:
#   publisher:
#   admins:
logo: /assets/images/seo/brand.png
# social:
#   name: Kurian
#   links:
#     - https://twitter.com/YOUR_TWITTER_HANDLE
#     - https://www.facebook.com/YOUR_FACEBOOK_HANDLE
#     - https://www.linkedin.com/in/YOUR_LINKEDIN_HANDLE
#     - https://github.com/YOUR_GITHUB_HANDLE
#     - https://keybase.io/YOUR_KEYBASE_HANDLE
